modLoader = "javafml"
loaderVersion = "[35,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/ActualLily/materialcabinet/issues"

[[mods]]
modId = "materialcabinet"
version = "${file.jarVersion}-0.1.0"
displayName = "Material Cabinet"
logoFile = "materialcabinet.png"
credits = "Thanks for this example mod goes to Java"
authors = "ActualLily"
description = '''
Embiggened storage.
'''
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"
